/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

use std::collections::HashSet;
use std::ffi::c_void;
use std::fmt;
use std::ptr::{self, NonNull};
use std::sync::OnceLock;

use embedder_traits::UntrustedNodeAddress;
use js::context::JSContext;
use js::conversions::FromJSValConvertible;
use js::glue::{
    CreateWrapperProxyHandler, GetProxyPrivate, GetProxyReservedSlot, ProxyTraps,
    SetProxyReservedSlot, WrapperNew,
};
use js::jsapi::{
    Handle as RawHandle, HandleId as RawHandleId, HandleObject as RawHandleObject,
    HandleValue as RawHandleValue, Heap, JS_DefineElement, JS_DefinePropertyById,
    JS_DeletePropertyById, JS_ForwardSetPropertyTo, JSContext as RawJSContext, JSErrNum, JSObject,
    JSPROP_ENUMERATE, ObjectOpResult, PropertyDescriptor, SetArrayLength,
};
use js::jsval::{ObjectValue, UndefinedValue};
use js::rust::{Handle, HandleId, HandleValue, MutableHandleValue, ToNumber};
use script_bindings::cell::DomRefCell;
use script_bindings::codegen::GenericBindings::DocumentBinding::DocumentMethods;
use script_bindings::codegen::GenericBindings::ShadowRootBinding::ShadowRootMethods;
use script_bindings::codegen::GenericBindings::WindowBinding::WindowMethods;
use script_bindings::conversions::{SafeToJSValConvertible, jsid_to_string, root_from_handlevalue};
use script_bindings::error::{Error, ErrorResult};
use script_bindings::reflector::DomObject;
use script_bindings::utils::get_array_index_from_id;
use servo_arc::Arc;
use servo_config::pref;
use style::media_queries::MediaList;
use style::shared_lock::{SharedRwLock as StyleSharedRwLock, SharedRwLockReadGuard};
use style::stylesheets::scope_rule::ImplicitScopeRoot;
use style::stylesheets::{Stylesheet, StylesheetContents};
use webrender_api::units::LayoutPoint;

use crate::dom::Document;
use crate::dom::bindings::codegen::Bindings::NodeBinding::GetRootNodeOptions;
use crate::dom::bindings::codegen::Bindings::NodeBinding::Node_Binding::NodeMethods;
use crate::dom::bindings::conversions::{ConversionResult, root_from_object_static};
use crate::dom::bindings::error::throw_dom_exception;
use crate::dom::bindings::inheritance::Castable;
use crate::dom::bindings::num::Finite;
use crate::dom::bindings::reflector::DomGlobal;
use crate::dom::bindings::root::{Dom, DomRoot, MutNullableDom};
use crate::dom::css::stylesheetlist::StyleSheetListOwner;
use crate::dom::customelementregistry::CustomElementRegistry;
use crate::dom::element::Element;
use crate::dom::globalscope::GlobalScope;
use crate::dom::node::{self, Node};
use crate::dom::types::{CSSStyleSheet, EventTarget, ShadowRoot};
use crate::dom::window::Window;
use crate::stylesheet_set::StylesheetSetRef;

/// Stylesheet could be constructed by a CSSOM object CSSStylesheet or parsed
/// from HTML element such as `<style>` or `<link>`.
#[derive(Clone, JSTraceable, MallocSizeOf)]
#[cfg_attr(crown, crown::unrooted_must_root_lint::must_root)]
pub(crate) enum StylesheetSource {
    Element(Dom<Element>),
    Constructed(Dom<CSSStyleSheet>),
}

impl StylesheetSource {
    pub(crate) fn get_cssom_object(&self) -> Option<DomRoot<CSSStyleSheet>> {
        match self {
            StylesheetSource::Element(el) => el.upcast::<Node>().get_cssom_stylesheet(),
            StylesheetSource::Constructed(ss) => Some(ss.as_rooted()),
        }
    }

    pub(crate) fn is_a_valid_owner(&self) -> bool {
        match self {
            StylesheetSource::Element(el) => el.as_stylesheet_owner().is_some(),
            StylesheetSource::Constructed(ss) => ss.is_constructed(),
        }
    }

    pub(crate) fn is_constructed(&self) -> bool {
        matches!(self, StylesheetSource::Constructed(_))
    }
}

#[derive(Clone, JSTraceable, MallocSizeOf)]
#[cfg_attr(crown, crown::unrooted_must_root_lint::must_root)]
pub(crate) struct ServoStylesheetInDocument {
    #[ignore_malloc_size_of = "Stylo"]
    #[no_trace]
    pub(crate) sheet: Arc<Stylesheet>,
    /// The object that owns this stylesheet. For constructed stylesheet, it would be the
    /// CSSOM object itself, and for stylesheet generated by an element, it would be the
    /// html element. This is used to get the CSSOM Stylesheet within a DocumentOrShadowDOM.
    pub(crate) owner: StylesheetSource,
}

// This is necessary because this type is contained within a Stylo type which needs
// Stylo's version of MallocSizeOf.
impl stylo_malloc_size_of::MallocSizeOf for ServoStylesheetInDocument {
    fn size_of(&self, ops: &mut stylo_malloc_size_of::MallocSizeOfOps) -> usize {
        <ServoStylesheetInDocument as malloc_size_of::MallocSizeOf>::size_of(self, ops)
    }
}

impl fmt::Debug for ServoStylesheetInDocument {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        self.sheet.fmt(formatter)
    }
}

impl PartialEq for ServoStylesheetInDocument {
    fn eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.sheet, &other.sheet)
    }
}

impl ::style::stylesheets::StylesheetInDocument for ServoStylesheetInDocument {
    fn enabled(&self) -> bool {
        self.sheet.enabled()
    }

    fn media<'a>(&'a self, guard: &'a SharedRwLockReadGuard) -> Option<&'a MediaList> {
        self.sheet.media(guard)
    }

    fn contents<'a>(&'a self, guard: &'a SharedRwLockReadGuard) -> &'a StylesheetContents {
        self.sheet.contents(guard)
    }

    fn implicit_scope_root(&self) -> Option<ImplicitScopeRoot> {
        None
    }
}

// https://w3c.github.io/webcomponents/spec/shadow/#extensions-to-the-documentorshadowroot-mixin
#[cfg_attr(crown, crown::unrooted_must_root_lint::must_root)]
#[derive(JSTraceable, MallocSizeOf)]
pub(crate) struct DocumentOrShadowRoot {
    window: Dom<Window>,
    custom_element_registry: MutNullableDom<CustomElementRegistry>,
}

impl DocumentOrShadowRoot {
    pub(crate) fn new(window: &Window) -> Self {
        Self {
            window: Dom::from_ref(window),
            custom_element_registry: MutNullableDom::new(None),
        }
    }

    /// <https://dom.spec.whatwg.org/#dom-documentorshadowroot-customelementregistry>
    pub(crate) fn custom_element_registry(&self) -> Option<DomRoot<CustomElementRegistry>> {
        self.custom_element_registry.get()
    }

    pub(crate) fn set_custom_element_registry(&self, registry: Option<&CustomElementRegistry>) {
        self.custom_element_registry.set(registry);
    }

    /// Retarget the result of `elementsFromPoint` or `elementFromPoint` according to the
    /// resolution in <https://github.com/w3c/csswg-drafts/issues/556>.
    pub(crate) fn retarget_hit_test_result(
        &self,
        this: &Node,
        node: DomRoot<Node>,
    ) -> Option<DomRoot<Element>> {
        let retargeted_node =
            DomRoot::downcast::<Node>(node.upcast::<EventTarget>().retarget(this.upcast()))?;
        DomRoot::downcast::<Element>(retargeted_node.clone()).or_else(|| {
            let parent_node = retargeted_node.GetParentNode()?;

            // This node has already been retargeted, but if it is the direct descendant of
            // a shadow root and it isn't an element, the only reasonable thing to return is
            // the shadow host (even though that is outside of `this`.) This is a surprising
            // behavior, but this is what browsers do.
            if let Some(shadow_root) = parent_node.downcast::<ShadowRoot>() {
                Some(shadow_root.Host())
            } else {
                retargeted_node.GetParentElement()
            }
        })
    }

    /// <https://drafts.csswg.org/cssom-view/#dom-document-elementfrompoint>
    #[expect(unsafe_code)]
    pub(crate) fn element_from_point(
        &self,
        this: &Node,
        x: Finite<f64>,
        y: Finite<f64>,
        document_element: Option<DomRoot<Element>>,
        has_browsing_context: bool,
    ) -> Option<DomRoot<Element>> {
        let x = *x as f32;
        let y = *y as f32;
        let viewport = self.window.viewport_details().size;

        if !has_browsing_context {
            return None;
        }

        if x < 0.0 || y < 0.0 || x > viewport.width || y > viewport.height {
            return None;
        }

        let results = self
            .window
            .elements_from_point_query(LayoutPoint::new(x, y));
        let Some(result) = results.first() else {
            return document_element;
        };

        // SAFETY: This is safe because `Self::query_elements_from_point` has ensured that
        // layout has run and any OpaqueNodes that no longer refer to real nodes are gone.
        let address = UntrustedNodeAddress(result.node.0 as *const c_void);
        let node = unsafe { node::from_untrusted_node_address(address) };

        self.retarget_hit_test_result(this, node)
    }

    /// <https://drafts.csswg.org/cssom-view/#dom-document-elementsfrompoint>
    #[expect(unsafe_code)]
    pub(crate) fn elements_from_point(
        &self,
        this: &Node,
        x: Finite<f64>,
        y: Finite<f64>,
        document_element: Option<DomRoot<Element>>,
        has_browsing_context: bool,
    ) -> Vec<DomRoot<Element>> {
        let x = *x as f32;
        let y = *y as f32;
        let viewport = self.window.viewport_details().size;

        if !has_browsing_context {
            return vec![];
        }

        // Step 2
        if x < 0.0 || y < 0.0 || x > viewport.width || y > viewport.height {
            return vec![];
        }

        // Step 1: Let sequence be a new empty sequence.
        // Step 3: For each box in the viewport, in paint order, starting with the topmost
        // box, that would be a target for hit testing at coordinates x,y even if nothing
        // would be overlapping it, when applying the transforms that apply to the
        // descendants of the viewport, append the associated element to sequence.
        let nodes = self
            .window
            .elements_from_point_query(LayoutPoint::new(x, y));

        let mut elements: Vec<_> = nodes
            .iter()
            .flat_map(|result| {
                // SAFETY: This is safe because `Self::query_elements_from_point` has ensured that
                // layout has run and any OpaqueNodes that no longer refer to real nodes are gone.
                let address = UntrustedNodeAddress(result.node.0 as *const c_void);
                let node = unsafe { node::from_untrusted_node_address(address) };
                self.retarget_hit_test_result(this, node)
            })
            .collect();

        // Now remove consecutive duplicates. This isn't in the specification, but it
        // follows browser behavior. See https://github.com/w3c/csswg-drafts/issues/556.
        let mut last_seen = None;
        elements.retain(|element| {
            if Some(element) == last_seen.as_ref() {
                return false;
            }
            last_seen = Some(element.clone());
            true
        });

        // Step 4: If the document has a root element, and the last item in sequence is
        // not the root element, append the root element to sequence.
        if let Some(root_element) = document_element &&
            elements.last() != Some(&root_element)
        {
            elements.push(root_element);
        }

        // Step 5: Return sequence.
        elements
    }

    /// <https://html.spec.whatwg.org/multipage/#dom-documentorshadowroot-activeelement-dev>
    pub(crate) fn active_element(&self, this: &Node) -> Option<DomRoot<Element>> {
        // Step 1. Let candidate be this's node document's focused area's DOM anchor.
        let document = self.window.Document();
        let candidate = document
            .focus_handler()
            .focused_area()
            .dom_anchor(&document);

        // Step 2. Set candidate to the result of retargeting candidate against this.
        //
        // Note: `retarget()` operates on `EventTarget`, but we can be assured that we are
        // only dealing with various kinds of `Node`s here.
        let candidate =
            DomRoot::downcast::<Node>(candidate.upcast::<EventTarget>().retarget(this.upcast()))?;

        // Step 3. If candidate's root is not this, then return null.
        if this != &*candidate.GetRootNode(&GetRootNodeOptions::empty()) {
            return None;
        }

        // Step 4. If candidate is not a Document object, then return candidate.
        if let Some(candidate) = DomRoot::downcast::<Element>(candidate.clone()) {
            return Some(candidate);
        }
        assert!(candidate.is::<Document>());

        // Step 5. If candidate has a body element, then return that body element.
        if let Some(body) = document.GetBody() {
            return Some(DomRoot::upcast(body));
        }

        // Step 6. If candidate's document element is non-null, then return that document element.
        if let Some(document_element) = document.GetDocumentElement() {
            return Some(document_element);
        }

        // Step 7. Return null.
        None
    }

    /// Remove a stylesheet owned by `owner` from the list of document sheets.
    #[cfg_attr(crown, expect(crown::unrooted_must_root))] // Owner needs to be rooted already necessarily.
    pub(crate) fn remove_stylesheet(
        owner: StylesheetSource,
        s: &Arc<Stylesheet>,
        mut stylesheets: StylesheetSetRef<ServoStylesheetInDocument>,
    ) {
        let guard = s.shared_lock.read();

        // FIXME(emilio): Would be nice to remove the clone, etc.
        stylesheets.remove_stylesheet(
            None,
            ServoStylesheetInDocument {
                sheet: s.clone(),
                owner,
            },
            &guard,
        );
    }

    /// Add a stylesheet owned by `owner` to the list of document sheets, in the
    /// correct tree position.
    #[cfg_attr(crown, expect(crown::unrooted_must_root))] // Owner needs to be rooted already necessarily.
    pub(crate) fn add_stylesheet(
        owner: StylesheetSource,
        mut stylesheets: StylesheetSetRef<ServoStylesheetInDocument>,
        sheet: Arc<Stylesheet>,
        insertion_point: Option<ServoStylesheetInDocument>,
        style_shared_lock: &StyleSharedRwLock,
    ) {
        debug_assert!(owner.is_a_valid_owner(), "Wat");

        if owner.is_constructed() && !pref!(dom_adoptedstylesheet_enabled) {
            return;
        }

        let sheet = ServoStylesheetInDocument { sheet, owner };

        let guard = style_shared_lock.read();

        match insertion_point {
            Some(ip) => {
                stylesheets.insert_stylesheet_before(None, sheet, ip, &guard);
            },
            None => {
                stylesheets.append_stylesheet(None, sheet, &guard);
            },
        }
    }

    /// Inner part of adopted stylesheet. This replaces the whole list at once, also for the
    /// single-element changes of the observable array (see [`AdoptedStyleSheets`]), rather
    /// than following the spec's per-index set and delete algorithms. The workflow here is
    /// actually following Gecko's implementation of AdoptedStylesheet before the
    /// implementation of ObservableArray.
    ///
    /// The main purpose from this function is to set the `&mut adopted_stylesheet` to match
    /// `incoming_stylesheet` and update the corresponding Styleset in a Document or a ShadowRoot.
    /// In case of duplicates, the setter will respect the last duplicates.
    ///
    /// <https://drafts.csswg.org/cssom/#dom-documentorshadowroot-adoptedstylesheets>
    // TODO: Handle duplicated adoptedstylesheet correctly, Stylo is preventing duplicates inside a
    //       Stylesheet Set. But this is not ideal. https://bugzilla.mozilla.org/show_bug.cgi?id=1978755
    fn set_adopted_stylesheet(
        cx: &mut JSContext,
        adopted_stylesheets: &mut Vec<Dom<CSSStyleSheet>>,
        incoming_stylesheets: &[Dom<CSSStyleSheet>],
        owner: &StyleSheetListOwner,
    ) -> ErrorResult {
        if !pref!(dom_adoptedstylesheet_enabled) {
            return Ok(());
        }

        let owner_doc = match owner {
            StyleSheetListOwner::Document(doc) => doc,
            StyleSheetListOwner::ShadowRoot(root) => root.owner_doc(),
        };

        for sheet in incoming_stylesheets.iter() {
            // > If value’s constructed flag is not set, or its constructor document is not equal
            // > to this DocumentOrShadowRoot’s node document, throw a "NotAllowedError" DOMException.
            if !sheet.constructor_document_matches(owner_doc) {
                return Err(Error::NotAllowed(None));
            }
        }

        // The set to check for the duplicates when removing the old stylesheets.
        let mut stylesheet_remove_set = HashSet::with_capacity(adopted_stylesheets.len());

        // Remove the old stylesheets from the StyleSet. This workflow is limited by utilities
        // Stylo StyleSet given to us.
        // TODO(stevennovaryo): we could optimize this by maintaining the longest common prefix
        //                      but we should consider the implementation of ObservableArray as well.
        for sheet_to_remove in adopted_stylesheets.iter() {
            // Check for duplicates, only proceed with the removal if the stylesheet is not removed yet.
            if stylesheet_remove_set.insert(sheet_to_remove) {
                owner.remove_stylesheet(
                    StylesheetSource::Constructed(sheet_to_remove.clone()),
                    &sheet_to_remove.style_stylesheet(),
                );
                sheet_to_remove.remove_adopter(owner);
            }
        }

        // The set to check for the duplicates when adding a new stylesheet.
        let mut stylesheet_add_set = HashSet::with_capacity(incoming_stylesheets.len());

        // Readd all stylesheet to the StyleSet. This workflow is limited by the utilities
        // Stylo StyleSet given to us.
        for sheet in incoming_stylesheets.iter() {
            // Check for duplicates.
            if !stylesheet_add_set.insert(sheet) {
                // The idea is that this case is rare, so we pay the price of removing the
                // old sheet from the styles and append it later rather than the other way
                // around.
                owner.remove_stylesheet(
                    StylesheetSource::Constructed(sheet.clone()),
                    &sheet.style_stylesheet(),
                );
            } else {
                sheet.add_adopter(owner.clone());
            }

            owner.append_constructed_stylesheet(cx, sheet);
        }

        *adopted_stylesheets = incoming_stylesheets.to_vec();

        Ok(())
    }
}

/// The `adoptedStyleSheets` list of a Document or ShadowRoot together with the observable
/// array exotic object that exposes it to script.
/// <https://webidl.spec.whatwg.org/#es-observable-array>
///
/// The bindings generator has no ObservableArray support, so the getter hands out a proxy
/// wrapping a plain backing array. The proxy's traps run every indexed and `length` mutation
/// through [`DocumentOrShadowRoot::set_adopted_stylesheet`] and only then mirror the result
/// into the backing array, so `push()`, `splice()` and index assignment restyle exactly like
/// assigning a whole new array.
#[derive(JSTraceable, MallocSizeOf)]
#[cfg_attr(crown, crown::unrooted_must_root_lint::must_root)]
pub(crate) struct AdoptedStyleSheets {
    sheets: DomRefCell<Vec<Dom<CSSStyleSheet>>>,
    #[ignore_malloc_size_of = "mozjs"]
    proxy: DomRefCell<Option<Heap<*mut JSObject>>>,
}

impl AdoptedStyleSheets {
    pub(crate) fn new() -> Self {
        Self {
            sheets: Default::default(),
            proxy: DomRefCell::new(None),
        }
    }

    fn rooted_sheets(&self) -> Vec<DomRoot<CSSStyleSheet>> {
        self.sheets
            .borrow()
            .iter()
            .map(|sheet| sheet.as_rooted())
            .collect()
    }

    /// <https://drafts.csswg.org/cssom/#dom-documentorshadowroot-adoptedstylesheets>
    #[expect(unsafe_code)]
    pub(crate) fn get(
        &self,
        cx: &mut JSContext,
        owner: &StyleSheetListOwner,
        mut retval: MutableHandleValue,
    ) {
        if let Some(proxy) = &*self.proxy.borrow() {
            retval.set(ObjectValue(proxy.get()));
            return;
        }

        rooted!(&in(cx) let mut backing = UndefinedValue());
        self.rooted_sheets().safe_to_jsval(cx, backing.handle_mut());
        rooted!(&in(cx) let backing = backing.to_object());
        rooted!(&in(cx) let proxy = unsafe {
            WrapperNew(
                cx.raw_cx(),
                backing.handle().into(),
                AdoptedStyleSheetsHandler::get().0,
                ptr::null(),
            )
        });
        assert!(!proxy.is_null());
        let owner_object = match owner {
            StyleSheetListOwner::Document(document) => document.reflector().get_jsobject().get(),
            StyleSheetListOwner::ShadowRoot(root) => root.reflector().get_jsobject().get(),
        };
        unsafe { SetProxyReservedSlot(proxy.get(), 0, &ObjectValue(owner_object)) };

        // Safety: the Heap has to be in its final memory location before it is set.
        *self.proxy.borrow_mut() = Some(Heap::default());
        self.proxy.borrow().as_ref().unwrap().set(proxy.get());
        retval.set(ObjectValue(proxy.get()));
    }

    /// <https://drafts.csswg.org/cssom/#dom-documentorshadowroot-adoptedstylesheets>
    pub(crate) fn set(
        &self,
        cx: &mut JSContext,
        owner: &StyleSheetListOwner,
        value: HandleValue,
    ) -> ErrorResult {
        match Vec::<DomRoot<CSSStyleSheet>>::safe_from_jsval(cx, value, ()) {
            Ok(ConversionResult::Success(sheets)) => self.replace(cx, owner, sheets),
            Ok(ConversionResult::Failure(msg)) => Err(Error::Type(msg.into_owned())),
            Err(_) => Err(Error::Type(
                c"The provided value is not a sequence of 'CSSStylesheet'.".to_owned(),
            )),
        }
    }

    /// Adopts `sheets` and mirrors them into the proxy's backing array, if script has seen it.
    #[expect(unsafe_code)]
    fn replace(
        &self,
        cx: &mut JSContext,
        owner: &StyleSheetListOwner,
        sheets: Vec<DomRoot<CSSStyleSheet>>,
    ) -> ErrorResult {
        rooted_vec!(let incoming <- sheets.iter().map(|sheet| sheet.as_traced()));
        DocumentOrShadowRoot::set_adopted_stylesheet(
            cx,
            &mut self.sheets.borrow_mut(),
            &incoming,
            owner,
        )?;

        let Some(proxy) = self.proxy.borrow().as_ref().map(|proxy| proxy.get()) else {
            return Ok(());
        };
        let mut slot = UndefinedValue();
        unsafe { GetProxyPrivate(proxy, &mut slot) };
        rooted!(&in(cx) let backing = slot.to_object());
        if !unsafe { SetArrayLength(cx.raw_cx(), backing.handle().into(), 0) } {
            return Err(Error::JSFailed);
        }
        for (index, sheet) in sheets.iter().enumerate() {
            rooted!(&in(cx) let mut value = UndefinedValue());
            sheet.safe_to_jsval(cx, value.handle_mut());
            if !unsafe {
                JS_DefineElement(
                    cx.raw_cx(),
                    backing.handle().into(),
                    index as u32,
                    value.handle().into(),
                    JSPROP_ENUMERATE as u32,
                )
            } {
                return Err(Error::JSFailed);
            }
        }
        Ok(())
    }

    /// Applies `mutate` to a copy of the adopted sheets and adopts the result. `mutate`
    /// returning false is the observable array handler returning false: the operation is
    /// rejected without a change, which throws only in strict mode.
    #[expect(unsafe_code)]
    fn mutate(
        &self,
        cx: &mut JSContext,
        owner: &StyleSheetListOwner,
        global: &GlobalScope,
        result: *mut ObjectOpResult,
        rejection: JSErrNum,
        mutate: impl FnOnce(&mut Vec<DomRoot<CSSStyleSheet>>) -> bool,
    ) -> bool {
        let mut sheets = self.rooted_sheets();
        if !mutate(&mut sheets) {
            unsafe { (*result).code_ = rejection as ::libc::uintptr_t };
            return true;
        }
        match self.replace(cx, owner, sheets) {
            Ok(()) => {
                unsafe {
                    (*result).code_ = 0 /* OkCode */
                };
                true
            },
            Err(Error::JSFailed) => false,
            Err(error) => {
                throw_dom_exception(cx, global, error);
                false
            },
        }
    }

    /// <https://webidl.spec.whatwg.org/#observable-array-exotic-object-set-the-indexed-value>
    fn set_indexed_value(
        &self,
        cx: &mut JSContext,
        owner: &StyleSheetListOwner,
        global: &GlobalScope,
        index: u32,
        value: HandleValue,
        result: *mut ObjectOpResult,
        rejection: JSErrNum,
    ) -> bool {
        let Ok(sheet) = root_from_handlevalue::<CSSStyleSheet>(cx, value) else {
            throw_dom_exception(
                cx,
                global,
                Error::Type(c"Value is not of type 'CSSStyleSheet'.".to_owned()),
            );
            return false;
        };
        let index = index as usize;
        self.mutate(cx, owner, global, result, rejection, |sheets| {
            if index > sheets.len() {
                return false;
            }
            if index == sheets.len() {
                sheets.push(sheet);
            } else {
                sheets[index] = sheet;
            }
            true
        })
    }

    /// <https://webidl.spec.whatwg.org/#observable-array-exotic-object-set-the-length>
    #[expect(unsafe_code)]
    fn set_length(
        &self,
        cx: &mut JSContext,
        owner: &StyleSheetListOwner,
        global: &GlobalScope,
        value: HandleValue,
        result: *mut ObjectOpResult,
        rejection: JSErrNum,
    ) -> bool {
        let Ok(number) = (unsafe { ToNumber(cx.raw_cx(), value) }) else {
            return false;
        };
        if number.fract() != 0.0 || !(0.0..=u32::MAX as f64).contains(&number) {
            throw_dom_exception(cx, global, Error::Range(c"Invalid array length".to_owned()));
            return false;
        }
        let new_length = number as usize;
        self.mutate(cx, owner, global, result, rejection, |sheets| {
            if new_length > sheets.len() {
                return false;
            }
            sheets.truncate(new_length);
            true
        })
    }
}

/// Runs `f` with the Document or ShadowRoot whose `adoptedStyleSheets` proxy is `proxy`.
#[expect(unsafe_code)]
fn with_adopted_stylesheets_owner<R>(
    proxy: *mut JSObject,
    f: impl FnOnce(&StyleSheetListOwner, &AdoptedStyleSheets, &GlobalScope) -> R,
) -> R {
    let mut slot = UndefinedValue();
    unsafe { GetProxyReservedSlot(proxy, 0, &mut slot) };
    let object = slot.to_object();
    if let Ok(document) = root_from_object_static::<Document>(object) {
        let owner = StyleSheetListOwner::Document(Dom::from_ref(&*document));
        return f(&owner, document.adopted_stylesheets(), &document.global());
    }
    let root = root_from_object_static::<ShadowRoot>(object)
        .expect("adoptedStyleSheets proxies are owned by a Document or a ShadowRoot");
    let owner = StyleSheetListOwner::ShadowRoot(Dom::from_ref(&*root));
    f(&owner, root.adopted_stylesheets(), &root.global())
}

fn is_length_id(cx: &JSContext, id: HandleId) -> bool {
    jsid_to_string(cx, id).is_some_and(|name| name == "length")
}

#[expect(unsafe_code)]
unsafe extern "C" fn adopted_stylesheets_set(
    cx: *mut RawJSContext,
    proxy: RawHandleObject,
    id: RawHandleId,
    v: RawHandleValue,
    receiver: RawHandleValue,
    res: *mut ObjectOpResult,
) -> bool {
    let mut cx = unsafe {
        // SAFETY: We are in SM hook
        JSContext::from_ptr(NonNull::new(cx).expect("JSContext should not be null in SM hook"))
    };
    let raw_id = id;
    let id = unsafe { Handle::from_raw(id) };
    let v = unsafe { Handle::from_raw(v) };
    let rejection = JSErrNum::JSMSG_PROXY_SET_RETURNED_FALSE;
    if let Some(index) = get_array_index_from_id(id) {
        return with_adopted_stylesheets_owner(*proxy, |owner, adopted, global| {
            adopted.set_indexed_value(&mut cx, owner, global, index, v, res, rejection)
        });
    }
    if is_length_id(&cx, id) {
        return with_adopted_stylesheets_owner(*proxy, |owner, adopted, global| {
            adopted.set_length(&mut cx, owner, global, v, res, rejection)
        });
    }
    let mut slot = UndefinedValue();
    unsafe { GetProxyPrivate(*proxy, &mut slot) };
    rooted!(&in(cx) let backing = slot.to_object());
    unsafe {
        JS_ForwardSetPropertyTo(
            cx.raw_cx(),
            backing.handle().into(),
            raw_id,
            v.into(),
            receiver,
            res,
        )
    }
}

#[expect(unsafe_code)]
unsafe extern "C" fn adopted_stylesheets_define_property(
    cx: *mut RawJSContext,
    proxy: RawHandleObject,
    id: RawHandleId,
    desc: RawHandle<PropertyDescriptor>,
    res: *mut ObjectOpResult,
) -> bool {
    let mut cx = unsafe {
        // SAFETY: We are in SM hook
        JSContext::from_ptr(NonNull::new(cx).expect("JSContext should not be null in SM hook"))
    };
    let raw_id = id;
    let id = unsafe { Handle::from_raw(id) };
    let index = get_array_index_from_id(id);
    let is_length = index.is_none() && is_length_id(&cx, id);
    if index.is_some() || is_length {
        let rejection = JSErrNum::JSMSG_PROXY_DEFINE_RETURNED_FALSE;
        let descriptor = unsafe { &*desc.ptr };
        // <https://webidl.spec.whatwg.org/#es-observable-array-defineProperty>
        // Indices and length only take writable, enumerable (for indices), configurable data
        // properties; anything else is rejected without a change.
        if descriptor.hasGetter_() ||
            descriptor.hasSetter_() ||
            !descriptor.hasValue_() ||
            (descriptor.hasConfigurable_() && !descriptor.configurable_()) ||
            (descriptor.hasWritable_() && !descriptor.writable_()) ||
            (index.is_some() && descriptor.hasEnumerable_() && !descriptor.enumerable_())
        {
            unsafe { (*res).code_ = rejection as ::libc::uintptr_t };
            return true;
        }
        rooted!(&in(cx) let value = descriptor.value_);
        return with_adopted_stylesheets_owner(*proxy, |owner, adopted, global| match index {
            Some(index) => adopted.set_indexed_value(
                &mut cx,
                owner,
                global,
                index,
                value.handle(),
                res,
                rejection,
            ),
            None => adopted.set_length(&mut cx, owner, global, value.handle(), res, rejection),
        });
    }
    let mut slot = UndefinedValue();
    unsafe { GetProxyPrivate(*proxy, &mut slot) };
    rooted!(&in(cx) let backing = slot.to_object());
    unsafe { JS_DefinePropertyById(cx.raw_cx(), backing.handle().into(), raw_id, desc, res) }
}

#[expect(unsafe_code)]
unsafe extern "C" fn adopted_stylesheets_delete(
    cx: *mut RawJSContext,
    proxy: RawHandleObject,
    id: RawHandleId,
    res: *mut ObjectOpResult,
) -> bool {
    let mut cx = unsafe {
        // SAFETY: We are in SM hook
        JSContext::from_ptr(NonNull::new(cx).expect("JSContext should not be null in SM hook"))
    };
    let raw_id = id;
    let id = unsafe { Handle::from_raw(id) };
    let rejection = JSErrNum::JSMSG_PROXY_DELETE_RETURNED_FALSE;
    // <https://webidl.spec.whatwg.org/#es-observable-array-deleteProperty>
    if let Some(index) = get_array_index_from_id(id) {
        let index = index as usize;
        return with_adopted_stylesheets_owner(*proxy, |owner, adopted, global| {
            adopted.mutate(&mut cx, owner, global, res, rejection, |sheets| {
                if index + 1 == sheets.len() {
                    sheets.pop();
                    true
                } else {
                    index >= sheets.len()
                }
            })
        });
    }
    if is_length_id(&cx, id) {
        unsafe { (*res).code_ = rejection as ::libc::uintptr_t };
        return true;
    }
    let mut slot = UndefinedValue();
    unsafe { GetProxyPrivate(*proxy, &mut slot) };
    rooted!(&in(cx) let backing = slot.to_object());
    unsafe { JS_DeletePropertyById(cx.raw_cx(), backing.handle().into(), raw_id, res) }
}

static ADOPTED_STYLESHEETS_PROXY_TRAPS: ProxyTraps = ProxyTraps {
    enter: None,
    getOwnPropertyDescriptor: None,
    defineProperty: Some(adopted_stylesheets_define_property),
    ownPropertyKeys: None,
    delete_: Some(adopted_stylesheets_delete),
    enumerate: None,
    getPrototypeIfOrdinary: None,
    getPrototype: None,
    setPrototype: None,
    setImmutablePrototype: None,
    preventExtensions: None,
    isExtensible: None,
    has: None,
    get: None,
    set: Some(adopted_stylesheets_set),
    call: None,
    construct: None,
    hasOwn: None,
    getOwnEnumerablePropertyKeys: None,
    nativeCall: None,
    objectClassIs: None,
    className: None,
    fun_toString: None,
    boxedValue_unbox: None,
    defaultValue: None,
    trace: None,
    finalize: None,
    objectMoved: None,
    isCallable: None,
    isConstructor: None,
};

/// Wrapper proxy handler for `adoptedStyleSheets` observable arrays; traps left unset forward
/// to the backing array, which keeps `Array.isArray()` and the Array.prototype methods working.
struct AdoptedStyleSheetsHandler(*const c_void);

// Safety: the handler is created once and all its C++ methods are const.
#[expect(unsafe_code)]
unsafe impl Send for AdoptedStyleSheetsHandler {}
// Safety: the handler is created once and all its C++ methods are const.
#[expect(unsafe_code)]
unsafe impl Sync for AdoptedStyleSheetsHandler {}

impl AdoptedStyleSheetsHandler {
    /// A single handler shared by every proxy and never freed, since the GC may reach it
    /// until the very end of the process.
    #[expect(unsafe_code)]
    fn get() -> &'static Self {
        static SINGLETON: OnceLock<AdoptedStyleSheetsHandler> = OnceLock::new();
        SINGLETON.get_or_init(|| {
            let handler = unsafe { CreateWrapperProxyHandler(&ADOPTED_STYLESHEETS_PROXY_TRAPS) };
            assert!(!handler.is_null());
            AdoptedStyleSheetsHandler(handler)
        })
    }
}
